name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo "🚀 Connected to EC2"

            cd /home/ec2-user/My_Portfolio

            echo "📥 Pulling latest code"
            git fetch origin
            git reset --hard origin/main

            echo "⚙️ Backend setup"
            cd backend
            npm install
            npm run build

            pm2 restart backend || pm2 start dist/index.js --name backend

            echo "🎨 Frontend build"
            cd ../frontend
            npm install
            npm run build

            echo "✅ Deployment completed"
